version: '3'
volumes:
  pgdata:
services:
  pg:
    image: postgres:10.3-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
  pg-test:
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_DB: app_test
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
  server:
    build: .
    volumes:
      - .:/app
    image: tonytonyjan/q_and_a
    ports:
      - '3000:3000'
    links:
      - pg
    env_file: .env
    command: ["sh", "-c", "rm -f tmp/pids/server.pid && bin/wait_for_pg bin/rails server"]
  test:
    build: .
    volumes:
      - .:/app
    image: tonytonyjan/q_and_a
    links:
      - pg-test
    environment:
      RAILS_ENV: test
    command: ["bin/wait_for_pg", "bin/rails", "test"]
  setup:
    build: .
    volumes:
      - .:/app
    image: tonytonyjan/q_and_a
    links:
      - pg
      - pg-test
    command: ["sh", "-c", "env RAILS_ENV=development bin/wait_for_pg true && env RAILS_ENV=test bin/wait_for_pg true && bin/setup"]
